apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auggie-demo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: auggie085/demo-asp-core
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: git@github.com:OgnjenNinkovic/DemoHelmRepo.git
    path: test_demo_app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
